export const colorsValuesMapping = {
  bands: [
    {
      colorBand: "1",
      colors: [
        { color: "Black", value: 0 },
        { color: "Brown", value: 1 },
        { color: "Red", value: 2 },
        { color: "Orange", value: 3 },
        { color: "Yellow", value: 4 },
        { color: "Green", value: 5 },
        { color: "Blue", value: 6 },
        { color: "Violet", value: 7 },
        { color: "primary-gray", value: 8 },
        { color: "White", value: 9 },
      ],
    },
    {
      colorBand: "2",
      colors: [
        { color: "Black", value: 0 },
        { color: "Brown", value: 1 },
        { color: "Red", value: 2 },
        { color: "Orange", value: 3 },
        { color: "Yellow", value: 4 },
        { color: "Green", value: 5 },
        { color: "Blue", value: 6 },
        { color: "Violet", value: 7 },
        { color: "primary-gray", value: 8 },
        { color: "White", value: 9 },
        { color: "Gold", value: -1 },
        { color: "Silver", value: -2 },
      ],
    },
    {
      colorBand: "3",
      colors: [
        { color: "Brown", value: "±1% (F)" },
        { color: "Red", value: "±2% (G)" },
        { color: "Orange", value: "±0.05% (W)" },
        { color: "Yellow", value: "±0.02% (P)" },
        { color: "Green", value: "±0.5% (D)" },
        { color: "Blue", value: "±0.25% (C)	" },
        { color: "Violet", value: "±0.1% (B)" },
        { color: "primary-gray", value: "±0.01% (L)" },
        { color: "Gold", value: "±5% (J)" },
        { color: "Silver", value: "±10% (K)" },
      ],
    },
    {
      colorBand: "4",
      colors: [
        { color: "Black", value: "250 ppm/K (U)" },
        { color: "Brown", value: "100 ppm/K (S)" },
        { color: "Red", value: "50 ppm/K (R)" },
        { color: "Orange", value: "15 ppm/K (P)" },
        { color: "Yellow", value: "25 ppm/K (Q)" },
        { color: "Green", value: "20 ppm/K (Z)" },
        { color: "Blue", value: "10 ppm/K (Z)" },
        { color: "Violet", value: "5 ppm/K (M)" },
        { color: "primary-gray", value: "1 ppm/K (K)" },
      ],
    },
  ],
};
